### ISSUE TITLE
Error thrown when attempting to delete a graph node

### ISSUE THREAD

**Issue by jaymehta-g** [Yogoda/Project-Map#7] opened 2022-12-23 17:17 UTC
After clicking on a node's con then pressing Delete, the error is thrown in the output:
` core/object.cpp:1242 - Error calling method from signal 'delete_nodes_request': 'GraphEdit(project_map.gd)::_on_GraphEdit_delete_nodes_request': Method expected 0 arguments, but called with 1..`

This happens with groups, comments, and file link nodes.

**Comment by Yogoda** [comment] 2022-12-24 11:53
Hello!

The issue is already fixed in the Github, please update with the latest version.

If you want to fix it manually, here is what to change:

- locate project_map.gd

change line 219
from: _on_GraphEdit_delete_nodes_request():
to:    _on_GraphEdit_delete_nodes_request(nodes = []):

Have a nice Christmas!
Joël

**Closed by Yogoda** 2022-12-24 11:53 UTC
